### ISSUE TITLE
[Android] Publish on F-Droid

### ISSUE THREAD

**Issue by linsui** [PurpleI2P/i2pd-android#4]
Would you please publish I2Pd on F-Droid?

**Comment by r4sas** [comment]
@IzzySoft can you validate that repo in your builder?
I'll move android codebase to current repository and added fastline.

**Comment by IzzySoft** [comment]
Which repo shall I validate in what builder? I'm at a loss here what you want me to do, sorry… If you ask about Telegram-FOSS and Fastlane: They now seem to use F-Droid internal metadata structures, which *might* work. I'd rather recommend using Fastlane structures (as linked above), as those are a standard.

**Comment by linsui** [comment]
I thought @r4sas is talking about **this repo**. The fastlane LGTM and it would be better to have some screenshots.

**Comment by IzzySoft** [comment]
Ah! So by "that repo" he meant "this repo" :see_no_evil: Then yes, ack on Fastlane. Though for end-users summary's probably not telling much ("Full-featured C++ implementation of I2P client" – they're unlikely to care about the programming language and might not even know what I2P is, so all what remains is "full featured client"). I couldn't even tell what *exactly* this app is after reading the full description. Educated guess: something like a "TOR proxy" running on the local device for other apps to use? Maybe include a [link to Wikipedia](https://en.wikipedia.org/wiki/I2P) for additional details? Screenshots would definitely help a lot as well to make things clearer.

**Comment by r4sas** [comment]
@IzzySoft how can I check if fdroidserver can build application correctly?
I tried to fill metadata and start `fdroid build org.purplei2p.i2pd`, but at end I got error:
```
2021-02-25 07:16:53,103 INFO: Cleaned build.gradle of keysigning configs at build/org.purplei2p.i2pd/app/build.gradle
2021-02-25 07:16:53,256 DEBUG: Updating main project
2021-02-25 07:16:53,280 ERROR: Could not build app org.purplei2p.i2pd: Android SDK tool android found!
```

In config.py I use this:
```
sdk_path = "/opt/android-sdk"
ndk_paths = {
      'r19c': "/opt/android-ndk-r19c",
}
build_tools = "29.0.3"
```

metadata:
```
...
RepoType: git
Repo: https://github.com/PurpleI2P/i2pd-android.git

Builds:
  - versionName: 2.36.0
    versionCode: 23600
    submodules: yes
    commit: 6ee4db6680b9ab1620d481eb09e9369bcf18916d
    ndk: r19c

AutoUpdateMode: None
UpdateCheckMode: None
CurrentVersion: 2.36.0
CurrentVersionCode: 23600
```

**Comment by linsui** [comment]
Add 
```yml
gradle:
  yes
```

**Comment by r4sas** [comment]
> Add
> 
> ```yaml
> gradle:
>   yes
> ```

Ah, thanks! Now waiting for build results.

**Comment by IzzySoft** [comment]
Thanks @linsui for picking up! I usually cannot answer many build-related question. In that section I'm an absolute novice, happy whenever the CI builds work out and often without a clue should they not… I have no own build env, so I cannot check myself.

**Comment by r4sas** [comment]
App was built successfully, but one problem is about multiple APK output with different ABI's, which rejected by builder.
In that case I must write few build records with different targets?

**Comment by linsui** [comment]
> In that case I must write few build records with different targets?

Yes, and autoupdate won't work.

**Comment by r4sas** [comment]
@linsui can you give example metadata with app, where auto-update works?

**Comment by linsui** [comment]
Sorry, I didn't make it clear. F-Droid can't autoupdate app with multiple abis. Maybe you can build a universal apk?

**Comment by r4sas** [comment]
Ah, I know that f-droid can't update in that case, so I already sed'ed split from true to false and restarted build.

**Comment by r4sas** [comment]
Successfully built.

```yaml
Categories:
  - Connectivity
  - Internet
  - Security
License: BSD-3-Clause
AuthorName: PurpleI2P
AuthorWebSite: https://i2pd.website/
WebSite: https://i2pd.website/
SourceCode: https://github.com/PurpleI2P/i2pd-android.git
IssueTracker: https://github.com/PurpleI2P/i2pd-android/issues
Changelog: https://github.com/PurpleI2P/i2pd/blob/openssl/ChangeLog
Bitcoin: 3MDoGJW9TLMTCDGrR9bLgWXfm6sjmgy86f
Litecoin: LKQirrYrDeTuAPnpYq5y7LVKtywfkkHi59

Name: i2pd
AutoName: i2pd

RepoType: git
Repo: https://github.com/PurpleI2P/i2pd-android.git

Builds:
  - versionName: 2.36.0
    versionCode: 23600
    submodules: yes
    commit: 6ee4db6680b9ab1620d481eb09e9369bcf18916d
    subdir: app
    gradle: yes
    prebuild:
      - sed -i -e 's/enable true/enable false/' build.gradle
    # Ignoring prebuilt opensource libraries
    scanignore:
      - app/jni/boost
      - app/jni/openssl
      - app/jni/miniupnp
    ndk: r19c

MaintainerNotes: Repo has metadata structure for description, title, images, etc

AutoUpdateMode: Version %v
UpdateCheckMode: Tags
CurrentVersion: 2.36.0
CurrentVersionCode: 23600
```

**Comment by linsui** [comment]
You need to build boost, openssl and miniupnp from source...

**Comment by r4sas** [comment]
Will think how to build them here...

**Comment by linsui** [comment]
[This](https://github.com/Gedsh/InviZible/blob/master/tordnscrypt/libs/build) may help. It clone the source and build them. A better method is include the source as submodule.

**Comment by r4sas** [comment]
Added building of external libraries from sources: https://github.com/PurpleI2P/i2pd-android/tree/extlibsrc

**Comment by r4sas** [comment]
Current code can be successfully compiled with this metadata:
```
Categories:
  - Connectivity
  - Internet
  - Security
License: BSD-3-Clause
AuthorName: PurpleI2P
AuthorWebSite: https://i2pd.website/
WebSite: https://i2pd.website/
SourceCode: https://github.com/PurpleI2P/i2pd-android.git
IssueTracker: https://github.com/PurpleI2P/i2pd-android/issues
Changelog: https://github.com/PurpleI2P/i2pd/blob/openssl/ChangeLog
Bitcoin: 3MDoGJW9TLMTCDGrR9bLgWXfm6sjmgy86f
Litecoin: LKQirrYrDeTuAPnpYq5y7LVKtywfkkHi59

Name: i2pd
AutoName: i2pd
Summary: Full-featured C++ implementation of I2P client
Description: |-
    <b>I2P</b> (Invisible Internet Protocol) is a universal anonymous network layer.
    All communications over I2P are anonymous and end-to-end encrypted, participants
    don't reveal their real IP addresses.

    <b>I2P client</b> is a software used for building and using anonymous I2P
    networks. Such networks are commonly used for anonymous peer-to-peer
    applications (filesharing, cryptocurrencies) and anonymous client-server
    applications (websites, instant messengers, chat-servers).

    <b>I2P</b> allows people from all around the world to communicate and share information
    without restrictions.

    For more information about <b>I2P</b>, you can read <a href="https://en.m.wikipedia.org/wiki/I2P">article on Wikipedia</a>.

RepoType: git
Repo: https://github.com/PurpleI2P/i2pd-android.git

Builds:
  - versionName: 2.40.0
    versionCode: 24000
    sudo:
      - apt-get update || apt-get update
      - apt-get install -y rename
    submodules: yes
    commit: 2.40.0-srclib
    subdir: app
    gradle: yes
    scanignore:
      # sources of openssl contains files, which detected as binaries
      - app/jni/openssl/fuzz
      - app/jni/openssl/boringssl/fuzz
    prebuild:
      - sed -i -e 's/enable true/enable false/' build.gradle
    build:
      - export ANDORID_SDK_ROOT=$$SDK$$
      - export ANDORID_NDK_HOME=$$NDK$$
      - pushd jni
      - ./build_boost.sh
      - ./build_openssl.sh
      - ./build_miniupnpc.sh
      - popd
    ndk: r21e

MaintainerNotes: Repo has metadata structure for description, title, images, etc

AutoUpdateMode: Version %v
UpdateCheckMode: Tags
CurrentVersion: 2.40.0
CurrentVersionCode: 24000
```
